// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Qs   = require("../src/qs.js");
var Qs$1 = require("qs");

var QuerySchema = /* module */[];

var Qs$2 = Qs.MakeQs(QuerySchema);

var parsed = Qs$1.parse("something=ok");

var match = parsed.something;

console.log(match !== undefined ? match : "not found");

exports.QuerySchema = QuerySchema;
exports.Qs          = Qs$2;
exports.parsed      = parsed;
/* Qs Not a pure module */
